[[Xorg_xcb_proto]]
arch = "armv7l"
git-tree-sha1 = "57a4478071fce09e17cc838d34096567d0c07d17"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "513d42014794656894dac15c223291a2d0647661c59d144b0916b5de012a59c3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "892dd7aefa50aa4b6f9e8e26694707b9ac800534"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "13655c638e49e2dec522a548a3904df67232ffd6e14061cd606668e791865f85"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.i686-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "606031b004dd30f8a841b1026c7881676fbd6c00"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "cbf04c39ecce618321fc0c058992d8962805d36b7e99d3d85d771606cc876958"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
git-tree-sha1 = "df29fb3e28cb699beab08bc056e1ba4bb4f82397"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "b1cd20212cf4d031f92415ff3aaca66b58eb8943e597e3d45d52bdb0d4319ec6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "14e6e0f4a4773997382cbe6b9cd19d9953e7e83c"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "735cd9b761609e8253e921a78aba617693c66a615bac3436ae6dfcd8918f141c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "5130ad359dafafecb15b74cdd421adc158cf2298"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "af186d4092e656781b05ecefceae49ead0eb5971dd97a7323b7d7b85bb5042ba"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "bc0758391e62c1cbdcb550a1a1278d71813e92a1"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "289d54b76da3b79bbf1e03f6d32af5f4e1acaeb7e513fe09fbbc6bef4a0ba9db"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.i686-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "8e91608a79e0fb28fbf8f8590ffe86c606ff46cd"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "eb6a5378986662e1cb0d3b59ac88ead5533f2c176179a72e25dd28f15d9b65f2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "5307cb96b3f71099c3940f6c4534c3d17f8b3474"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "ee705b71a2dea6ac733054c8927605664e70243eccc666fe3137b79f085a0629"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "powerpc64le"
git-tree-sha1 = "8c01f1b04942cb7768a8e8edd0d7806f363735dd"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "d9335def011b068b6a34dcc611bb7c961e2c95bea6358b44e00fa70ce9963426"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.13.0+1/Xorg_xcb_proto.v1.13.0.powerpc64le-linux-gnu.tar.gz"
