[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "d656af1bd56c917cb133835f317d6380012d399b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "3b0c883221533cb7f2a9af22a8ea260b686698c3e67e212f67e900a894aa17f8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "0feb9a9a583b3d073bb6a50c4c8acbf98fd4b0a7"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "f8eeba7115aee4c6525229947aedc11e9ff4dabd5a4e4c442b8484cd0aa52ad5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "a422b6a7dbc3d528f90bc6b5eab91fb0a200c288"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "c8e61ac6975198b3c4589c4e16d44a0b93d0c5f8eb332da71f5b987c6921962a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12f88bc4f8693c8246f21af314923df952a03118"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "1cf591b99e6c359bd9b68a78e863542fae53fe696469a20e499f940cf2a21c5b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2eecbf2636f93c4030ac71adaf1002d4a1b4d711"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "9f5193464b7e31cde60c43393b1b286d69b81676d89d4b6db41e387beb14cbaa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3dc067d42430d055be9439176afb7b6ddd4e3d03"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "471817682a8bc70fe438915e0a0532e8fff8e3e8d3f7c6199eca30e45ef79f57"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9e553229fa6d3feed1c3b50eaff04b0a7a393f3"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "9cbb95af6ecf73dcc8e571b5e8964baf529d3075f2d62fa30979886364105461"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "e644ea08da217888fd456d12e60181c9b0b3e08c"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "3af20da265f94140a6fe44283aeb37781705cba05fae6199872e9e413ee9b841"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.i686-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "0feb9a9a583b3d073bb6a50c4c8acbf98fd4b0a7"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "f8eeba7115aee4c6525229947aedc11e9ff4dabd5a4e4c442b8484cd0aa52ad5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.i686-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "powerpc64le"
git-tree-sha1 = "0feb9a9a583b3d073bb6a50c4c8acbf98fd4b0a7"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "f8eeba7115aee4c6525229947aedc11e9ff4dabd5a4e4c442b8484cd0aa52ad5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "riscv64"
git-tree-sha1 = "12f88bc4f8693c8246f21af314923df952a03118"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "1cf591b99e6c359bd9b68a78e863542fae53fe696469a20e499f940cf2a21c5b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.riscv64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "3dc067d42430d055be9439176afb7b6ddd4e3d03"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "471817682a8bc70fe438915e0a0532e8fff8e3e8d3f7c6199eca30e45ef79f57"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "0feb9a9a583b3d073bb6a50c4c8acbf98fd4b0a7"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "f8eeba7115aee4c6525229947aedc11e9ff4dabd5a4e4c442b8484cd0aa52ad5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "6d427a2204619fe5818633add35ecbcb95bf87a1"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "9eab7dc0136e654b9e95fb681f57796f291b8837d01153d3cc786e81ec63f5c7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+2/Xorg_xcb_proto.v1.17.0.x86_64-unknown-freebsd.tar.gz"
