[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "c759d1f3041771af291520f2b69a4b642144575f"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "ba6f297bcb45b14e8e55ec6c1290771ad5fea985b9e35d7cad12a7dd61d651a8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "4e4d4737d12f57f925f34ad6acf87a88e3f89bfd"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "79d50f69b53a6b6b239b123ca334596eb1bb17fb76cd8c2066217fc37b8e3f82"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "3085cdb374081bda48a203ed6aa579c7d0810186"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "5d7ca3c7448cee1cec02913edf151fda5c1585b1aaffd428f91717772fae6a26"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd8e1ecdebfd7583a69eda5287f6f0293674cb8a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "6e77e3a3874fb311d2721ca59b4d3f71b0b3a7241d94e2b832c493d620cea155"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c668746bb3022be7cc2215d3682dbb778ae38bf"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "a8ff3e2dd87d72b5f2273100e68458f0691b402f831285bfa3e272f9b9b0067f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f056f8317d272de8065bbaa514de0d3490c266d3"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "78e762e85b04194c590c624352a1ee4c98734881b1ff278d8bfce0a6442e172c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eaeb7e403886192293a7289c12398a52fb8e2afc"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "5eac7bed7ab209207deed1fef76383d4e87b794db104941bab25df5e899655a7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "ec661173f71263a55d61956f92617519ffc7d764"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "e2c90bdaeccb69c8c044b5ac5d6a89f0107ae0c689e1e8bf55109f54665ac2b6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.i686-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "5c7d33a9bddeca197cf981b2a94c6eb77468f341"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "9d6195e48748af6fe134023fa705832193aece02de06ab83dd1b7605bbcffc1f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.i686-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "powerpc64le"
git-tree-sha1 = "05a6dd0c61261d2da73f1d08b8c6bab6ad3623cd"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "11f8f0c0fe944c9a6c7c5d8cb4858d22826e35790b2d31a22962f4122c824e73"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "riscv64"
git-tree-sha1 = "f10f0f8f55ad6b5688f2d5f9f25450c0051ca18a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "c28d8fe2b935ac28adbd380d67dfc0eea6cc775db26fac18b01ec68ed9421886"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.riscv64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "8341a0d9c24278ef19ef16011d28060af2d0d56a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "5bc7d59c5e9f10282abdabb3b033fb91e3bb1f5f94982c9705393cd81aa57f3e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "e8eac6282cd46e2fe8349cdc50aa34a356fdf2c8"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "8bc9399c7494a34d4172708b90102ddeae98b7c7db016c5a5faf69ba9fea26b1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "4f2651490963df1b77febfc18017ae764afb1fe0"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "e7d02ebfaace1ce4926af670c8641012afd923af61cebb8cc0d45b0e98aff889"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.1+0/Xorg_xcb_proto.v1.17.1.x86_64-unknown-freebsd.tar.gz"
