[Xorg_xcb_proto]
git-tree-sha1 = "744f6d3445d4c955f46022adf15ee5964f880a94"

    [[Xorg_xcb_proto.download]]
    sha256 = "e968cdf07eea9fe297b95318d3bf1be8e867a84ea3f5ec2f6d383788b73ad507"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.2+0/Xorg_xcb_proto.v1.17.2.any.tar.gz"
