[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "21d2ca8806518030cab25e729c52deafd061f4dc"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "8e190a83273511250a18202113142319820bc7a9cb32d9104f58a4ad2cccbaa3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "aarch64"
git-tree-sha1 = "df95ea5e0755165005f1342dd69982ba640ca5d1"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "365242582f12773e34574b8910f39d1da8de1c1766e8d9ffa2452f19faf37fae"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c0a5efcbd35e4887cdd0260263a6f2e9e5aed95a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "be94576455088663184979ba259e01a8636c3c11e7b33357cd8eb7b7e532efdf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05045de9dc2a4ca2ab59eab8b3201fa5b03d30f0"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "03c5ee3e72af26fa10913a89ca24bd41fd07ad1bd5c81c0d8519555c736d72d6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1fc2676a6b2c6b36c7f842e5fc10c40fa6964e1b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "0e5f0126614b310336c5093d796cc7b02f32d90ed67794d2b6f7a1abb516617d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "444bf24fca8258ed2d737efc0321d0629adf32fe"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "7510a5e7e3dc4d0fe9a7a6bf61c10660ff1288bd6242f21b04e03696e2bdce54"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "8e77d81875262a03344559ee6e29247b5a1e4152"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "44a0b509149b3da69636ed7be132ce3c562ed4cd1aa385df78e98320230c693b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.i686-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "i686"
git-tree-sha1 = "21d2ca8806518030cab25e729c52deafd061f4dc"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "8e190a83273511250a18202113142319820bc7a9cb32d9104f58a4ad2cccbaa3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.i686-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "powerpc64le"
git-tree-sha1 = "1fc2676a6b2c6b36c7f842e5fc10c40fa6964e1b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "0e5f0126614b310336c5093d796cc7b02f32d90ed67794d2b6f7a1abb516617d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "df95ea5e0755165005f1342dd69982ba640ca5d1"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "365242582f12773e34574b8910f39d1da8de1c1766e8d9ffa2452f19faf37fae"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "1fc2676a6b2c6b36c7f842e5fc10c40fa6964e1b"
libc = "musl"
os = "linux"

    [[Xorg_xcb_proto.download]]
    sha256 = "0e5f0126614b310336c5093d796cc7b02f32d90ed67794d2b6f7a1abb516617d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_proto]]
arch = "x86_64"
git-tree-sha1 = "df95ea5e0755165005f1342dd69982ba640ca5d1"
os = "freebsd"

    [[Xorg_xcb_proto.download]]
    sha256 = "365242582f12773e34574b8910f39d1da8de1c1766e8d9ffa2452f19faf37fae"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_proto_jll.jl/releases/download/Xorg_xcb_proto-v1.17.0+0/Xorg_xcb_proto.v1.17.0.x86_64-unknown-freebsd.tar.gz"
