# Autogenerated wrapper script for Xorg_xcb_proto_jll for i686-linux-gnu
JLLWrappers.@generate_wrapper_header("Xorg_xcb_proto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
